### ISSUE TITLE
The Slice Mesh & Truncate options panel don't show

### ISSUE THREAD

**Issue by Oxervision** [Lichtso/curve_cad#1]
First, thanks for the addon!!
I have tested the addon on macos 11.3.6 & Blender 2.80.55 and all works fine except that the options panel for Slice Mesh & Truncate don't show, in the case of Slide Mesh generates 9 slices only and the spacing between slices is 10cm. Respect to Truncate the options panel don't show too.

**Comment by Lichtso** [comment]
This should be fixed now.

However, there is still a bug in Blender 2.80 which causes it to crash when changing parameters of the slice mesh operator: https://developer.blender.org/T63483

**Comment by Oxervision** [comment]
Thanks for your effort and the info, I'll test it and I infom you.

**Comment by Oxervision** [comment]
The panels are showed now and yes, when you try to change the parameters of Slice Mesh, Blender crash.

**Comment by Oxervision** [comment]
I have added 'USE_EVAL_DATA' to the operator:
```
class SliceMesh(bpy.types.Operator):
    bl_idname = 'curve.add_toolpath_slice_mesh'
    bl_description = bl_label = 'Slice Mesh'
    bl_options = {'REGISTER', 'UNDO', 'USE_EVAL_DATA'}
```
This fixed the issue with Slice Mesh, it works fine now.

**Comment by Lichtso** [comment]
Thanks, I will include the fix in the next commit.

On a side note: I have been thinking of replacing the axis and offset parameters of the slicing operator by an empty object, similar to the truncate operator. This way it might be easier to configure the slicing as you could visually see it (as cube or plane). Do you think that makes sense?

**Comment by Oxervision** [comment]
I think the current layout is good and easy to use perhaps you could place the specific description in Pitch & Axis (see the image) and its corresponding tooltip for each one, explaning the function, I don't know if this is possible.

![Names Description](https://user-images.githubusercontent.com/46649474/56038467-522dec00-5d32-11e9-97a7-31324ccc19bf.jpg)
