### ISSUE TITLE
Make separate branch for Blender 2.7x

### ISSUE THREAD

**Issue by ghost** [Lichtso/curve_cad#2]
Please, create separate repo with version for Blender 2.7x

**Comment by Lichtso** [comment]
A separate repo would be over the top, but I created a branch here:
https://github.com/Lichtso/curve_cad/tree/Blender27X

**Comment by ghost** [comment]
Oh, I mean ~~repo~~ branch.

**Comment by ghost** [comment]
Also, it would be cool if bug fixes & features would be backported from `master` to `Blender27X` (if possible).

**Comment by Lichtso** [comment]
Done: 6fee5204cce44784896144e25967e9a872019f47
You can download it from the Blender27X branch.
