### ISSUE TITLE
no have module named curve_cad

### ISSUE THREAD

**Issue by DarthMoulByte** [Lichtso/curve_cad#6]
i use my own fork of Blender 2.83 lts

when i try to active the addon , any idea to fix ?

![image](https://user-images.githubusercontent.com/24207840/86150827-87536500-bac3-11ea-8acb-af047059bfe7.png)

**Comment by Lichtso** [comment]
The directory name of the add-on `curve_cad-Update-to-2.80-master` contains a dot and that seems to cause confusion (maybe interpreted as file extension). So, it seems to search for `curve_cad-Update-to-2` which does not exist. Try renaming the directory to something without a dot.
